name: dirac-cwl
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
      - cwl-utils
      - cwlformat
      - cwltool
      - lbprodrun
      - mypy
      - pre-commit
      - pydantic
      - pytest
      - typer
      - rich
      - ruamel.yaml
